### ISSUE TITLE
REQ_WCAG_1.2.3 Audio Description or Media Alternative (Prerecorded)

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#11]
# GUIDELINE
## Principle

**PERCEIVABLE**
> Information and user interface components must be presentable to users in ways they can perceive. This means that users must be able to perceive the information being presented (it can't be invisible to all of their senses) Provide text alternatives for non-text content. Provide captions and other alternatives for multimedia. Create content that can be presented in different ways, including by assistive technologies, without losing meaning. Make it easier for users to see and hear content. 

## Level of Conformance 
**A** 
> (the minimum level of conformance), the Web page satisfies all the Level A Success Criteria, or a conforming alternate version is provided.

## Referenced Requirements

> 1.2.3, 1.2.5 (#11), and 1.2.8(#12) overlap somewhat with each other. This is to give the author some choice at the minimum conformance level, and to provide additional requirements at higher levels. At Level A in Success Criterion 1.2.3, authors do have the choice of providing either an audio description or a full text alternative. If they wish to conform at Level AA, under Success Criterion 1.2.5 authors must provide an audio description - a requirement already met if they chose that alternative for 1.2.3, otherwise an additional requirement. At Level AAA under Success Criterion 1.2.8 they must provide an extended text description. This is an additional requirement if both 1.2.3 and 1.2.5 were met by providing an audio description only. If 1.2.3 was met, however, by providing a text description, and the 1.2.5 requirement for an audio description was met, then 1.2.8 does not add new requirements.

## General description
 An alternative for time-based media or audio description of the prerecorded video content is provided for synchronized media, except when the media is a media alternative for text and is clearly labeled as such.

## Intent
One approach is to provide audio description of the video content. The audio description augments the audio portion of the presentation with the information needed when the video portion is not available. During existing pauses in dialogue, audio description provides information about actions, characters, scene changes, and on-screen text that are important and are not described or spoken in the main sound track.

The second approach involves providing all of the information in the synchronized media (both visual and auditory) in text form. An alternative for time-based media provides a running description of all that is going on in the synchronized media content. The alternative for time-based media reads something like a screenplay or book. Unlike audio description, the description of the video portion is not constrained to just the pauses in the existing dialogue. Full descriptions are provided of all visual information, including visual context, actions and expressions of actors, and any other visual material. In addition, non-speech sounds (laughter, off-screen voices, etc.) are described, and transcripts of all dialogue are included. The sequence of description and dialogue transcripts are the same as the sequence in the synchronized media itself. As a result, the alternative for time-based media can provide a much more complete representation of the synchronized media content than audio description alone.

## Examples
1. A movie with audio description.
Describer: A title, "Teaching Evolution Case Studies. Bonnie Chen." A teacher shows photographs of birds with long, thin beaks.
Bonnie Chen: "These photos were all taken at the Everglades."
Describer: The teacher hands each student two flat, thin wooden sticks.
Bonnie Chen: "Today you will pretend to be a species of wading bird that has a beak like this."
Describer: The teacher holds two of the sticks to her mouth making the shape of a beak.
Transcript of audio based on the first few minutes of " Teaching Evolution Case Studies, Bonnie Chen" (copyright WGBH and Clear Blue Sky Productions, Inc.)
2. An alternative for time-based media for a training video
A company purchases a Training video for use by its employees and puts it on the companies intranet. The video involves explaining use of a new technology and has a person talking and showing things at the same time. Since there is no place to insert audio description of the visual demonstrations during gaps in dialogue, the company provides an alternative for time-based media that all employees, including those who cannot see the demonstrations, can use to better understand what is being presented.

## Sufficient Techniques

> Sufficient techniques are reliable ways to meet the success criteria.
> - From an author's perspective: If you use the sufficient techniques for a given criterion correctly and it is accessibility-supported for your users, you can be confident that you met the success criterion.
> - From an evaluator's perspective: If web content implements the sufficient techniques for a given criterion correctly and it is accessibility-supported for the content's users, it conforms to that success criterion. (The converse is not true; if content does not implement these sufficient techniques, it does not necessarily fail the success criteria, as explained in Testing Techniques below.)
> There may be other ways to meet success criteria besides the sufficient techniques in W3C's Techniques for WCAG document, as Other Techniques below. (See also Techniques are Informative above.)

NOTE: I'm not listing all techniques, for all options see full documentation

- G69
- G78
- G203

### [IG69: Providing an alternative for time based media](https://www.w3.org/WAI/WCAG21/Techniques/general/G69) using one of the following techniques
- [G58: Placing a link to the alternative for time-based media immediately next to the non-text content](https://www.w3.org/WAI/WCAG21/Techniques/general/G58)
> A link to the collated document of audio description is immediately adjacent to the non-text content. The link can be immediately before or after the synchronized media content. If the collated document is on the same Web page as other content then put "End of document" at the end so that they know when to stop reading and return to their previous place. If a Back button will not take the person back to the point from which they jumped, then a link back to the non-text content location is provided.

**Example**
Code on a page called "Olympic_Sports.htm"

```
  <a name="Olympic_Wrestling"></a>
  <p><a href="http://www.example.com/movies/olympic_wrestling.mov">Olympic Wrestling movie</a>, 
  <a href="http://www.example.com/transcripts/olympic_wrestling_transcript.htm">Olympic 
  Wrestling collated Transcript</a></p>
```
Code on the page olympic_wrestling_transcript.htm
```
  <p>Sports announcer 1: This is a great battle tonight between England's "Will Johnson" and 
  "Theodore Derringo" from Argentina</p>
  <p>Scenery: There is a mat set out in the middle of the stadium with 500 people in the 
  stands...</p>
  <p> ...more dialogue...<p>
  <p> ...more scenery...</p>
  <p> ...etc...</p>
  <p>Sports announcer 2: And that is all for tonight, thank you for joining us tonight where 
  Will Johnson is the new Gold Medalist. 
  <a href="../movies/Olympic_Sports.htm#Olympic_Wrestling>Return to Movie page</a> </p>
         
```
### Test Procedure

1. Check for the presence of a link immediately before or after the non-text content.
2. Check that it is a valid link that points directly to the collated document of this particular synchronized media.
3. Check for the availability of a link or back function to get the user back to the original location of the synchronized media content.

**Expected Results**

Items # 1 through 3 are all true.

### [G78: Providing a second, user-selectable, audio track that includes audio descriptions](https://www.w3.org/WAI/WCAG21/Techniques/general/G78)
> The objective of this technique is to provide an audio (spoken) version of information that is provided visually so that it is possible for people who cannot see to be able to understand audio-visual material.

**Example**

1. A travelogue of the northeast has additional audio description added during the gaps in the dialogue to let listeners who are blind know what the person is talking about at any point in time.
2. A video shows a woodpecker carving a nest in a tree. A button within the content allows users to turn the audio description track on or off.
3. A lecture has audio description added whenever the instructor says things like "and this is the one that is most important." The audio descriptions lets listeners who can not see the video know what "this" is.
4. A movie file has two audio tracks, one of which includes audio description. Users can choose either one when listening to the movie by selecting the appropriate track in their media player.

### Test Procedure

1. Check that the ability exists to turn on the audio track that includes audio descriptions. For example, by using a control within the content itself or by selecting a control or preference in the media player or operating system.
2. Listen to the synchronized media
3. Check to see if gaps in dialogue are used to convey important information regarding visual content

**Expected Results**

Checks # 1 and # 3 are true.

### [G203: Using a static text alternative to describe a talking head video](https://www.w3.org/WAI/WCAG21/Techniques/general/G203)
> The purpose of this technique is to provide an alternative to audio description (...) This particularly applies to "talking head" videos where a person is talking in front of an unchanging background, such as a press conference, company president talk, or government announcement, etc. In this case there are no "important visual details" which would warrant audio description.

**Example**
1. A video of a CEO speaking to shareholders
A CEO is speaking to shareholders from his office. The video has a title page at the beginning of the video giving the date. When the speaker begins, there is a strip of text at the bottom of the video saying "John Doe, President of XYZ Cooperation". At the end of the video are title credits that say "produced by the Honest TV Productions Ltd."
As an alternative, there is a paragraph below the video which is associated with the video file using aria-describedby which says: "July 22, 2011, John Doe, President of XYZ cooperation, speaking from his office. Video produced by the Honest TV Productions Ltd."

### Test Procedure

1. Check that there is no important time-based information in the video track
2. Check that the programmatically associated description of the media contains any context of the content that is not contained in the audio track (e.g. speaker identification, credits, context)

**Expected Results**

All checks are true.

## Advisory Techniques

> Advisory techniques are suggested ways to improve accessibility. They are often very helpful to some users, and may be the only way that some users can access some types of content.
> Advisory techniques are not designated as sufficient techniques for various reasons such as:
> - they may not be sufficient to meet the full requirements of the success criteria;
> - they may be based on technology that is not yet stable;
> - they may not be accessibility supported in many cases (for example, assistive technologies do not work with them yet);
> - they may not be testable;
> - in some circumstances they may not be applicable or practical, and may even decrease accessibility for some users while increasing it for others;
> - they may not address the success criterion itself, and instead provide related accessibility benefits.
> Authors are encouraged to apply all of the techniques where appropriate to best address the widest range of users' needs.

### [H96: Using the track element to provide audio descriptions](https://www.w3.org/WAI/WCAG21/Techniques/html/H96)
>  use the HTML5 track element to specify a descriptions timed text track for a video element. Audio description timed text tracks contain textual descriptions of the video component of the media resource, intended for audio synthesis when the visual component is obscured, unavailable, or not usable.

> :exclamation: IMPLEMENTATION ALERT As of February 2019 when this Advisory technique was last reviewed by the Working Group, there is no native support in user agents for this technique. However, support is available via JavaScript polyfills.

**Example**
```
<video poster="myvideo.png" controls>
  <source src="myvideo.mp4" srclang="en" type="video/mp4">
  <source src="myvideo.webm" srclang="fr" type="video/webm">
  <track src="myvideo_en.vtt" kind="descriptions" srclang="en" label="English">
  <track src="myvideo_fr.vtt" kind="descriptions" srclang="fr" label="French">
</video>   
```
### Test Procedure

For each video element used to play a video:
1. Check that the video contains a track element of kind descriptions in the language of the video.

**Expected Results**

Check # 1 is true.

# SELI CONTEXT

## Tasks
List the tasks required to accomplish the requirement (not exhaustive)

- [ ] **SYSTEM** MUST include SELI's videos contents with audio-description for all videos that student may consume.

- When TEACHER uploads a video content (not video-only)
  - [ ] SYSTEM MUST provide a checkbox to TEACHER marks if it is a video-only.

- IF TEACHER uploads a video content, i.e. video-only checkbox not checked
  - [ ] SYSTEM MUST provide a checkbox to TEACHER marks if the video has audio-description embedded.

- IF TEACHER uploads a video content without embedded audio-description, i.e. embedded audio-description checkbox not checked
  - [ ] SYSTEM MUST provide a checkbox to TEACHER marks if the video is a TALKING HEAD

- IF TEACHER uploads a TALKING HEAD video content, i.e. talking head checkbox  checked
  - SYSTEM MUST guide TEACHER to writes/paste the video description in the SHORT DESCRIPTION field.

- IF TEACHER don't uploads a TALKING HEAD video content, i.e. talking head checkbox not checked
  - [ ] SYSTEM MUST provide
    - an option to TEACHER write/paste a text transcription; OR
    - an option to TEACHER uploads an second audio track; OR
    - an option to TEACHER uploads an audio-description  track (:exclamation: .vtt file)

- SYSTEM MUST render teacher's video content with it audio-description or media alternatives, if teacher configure one.

# Suggested implementation

```
<!-- SEIZURE (if risk is true ) -->
<input type="checkbox" value="aware" aria-expanded="false" aria-controls="id_video_box">This video is hidden because has seizure risks, choose this option to show the video</button>
<div id="id_video_box">
   <h3>Video title</h3>
   <p id="id_short_desc"><!-- SHORT DESCRIPTION / TALKING HEAD DESCRIPTION G203--></p>
   <h3><button aria-expanded="false" aria-controls="id_req_acc">Available accessibility resources</button></h3>
   <ul id="id_req_acc">
  	<li>Audio description</li>
  	<li>Closed captions</li>
 	<li>Transcriptions</li>
  	<li>Sign Language</li>
   </ul>
   <video id=video poster="poster.png" autoplay="false" aria-label="id_short_desc" aria-describedby="id_long_desc">
       <source id='mp4' src="trailer.mp4" type='video/mp4'/>
       <!-- Track to be used for CAPTIONS H95 -->
       <track kind="captions" label="English[cc]" src="captions_en.vtt" srclang="en" default></track>
       <!-- Track to be used for AUDIO-DESCRIPTION as .vtt  H96-->
       <track kind="descriptions" label="English[desc]" src="audiodesc_de.vtt" srclang="en"></track>
       <p>Your user agent does not support the HTML5 Video element.</p>
   </video>
</div>

<button aria-expanded="false" aria-controls="id_long_desc">Video Transcription</button>
<div><p  id="id_long_desc"><!-- TRANSCRIPTIONS G58 --></p></div>
```
## Resources

For G78
- [HTML5 multi-track audio or video](https://gingertech.net/2011/05/01/html5-multi-track-audio-or-video/)
- [Codepen.io Example](https://codepen.io/team/rcrooks1969/pen/LoWNQy) 
- [Howler.js](https://github.com/goldfire/howler.js)
- 

# :notebook_with_decorative_cover:   References

- [How to Meet WCAG (Quick Reference)](https://www.w3.org/WAI/WCAG21/quickref/#audio-only-and-video-only-prerecorded)
- [Understanding Techniques for WCAG Success Criteria](https://www.w3.org/WAI/WCAG21/Understanding/understanding-techniques)

# GLOSSARY 
- SELI's content: all contents not created by users (e.g. seli "about" section text)

:warning: The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119/8174](http://www.rfc-editor.org/info/rfc8174).
> 1. **MUST** This word, or the terms "REQUIRED" or "SHALL", mean that the definition is an absolute requirement of the specification.
> 2. **MUST NOT** This phrase, or the phrase "SHALL NOT", mean that the definition is an absolute prohibition of the specification.
> 3. **SHOULD** This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.
> 4. **SHOULD NOT** This phrase, or the phrase "NOT RECOMMENDED" mean that there may exist valid reasons in particular circumstances when the particular behavior is acceptable or even useful, but the full implications should be understood and the case carefully weighed before implementing any behavior described with this label.
> 5. **MAY**   This word, or the adjective "OPTIONAL", mean that an item is truly optional. An implementation which does not include a particular option MUST be prepared to interoperate with another implementation which does include the option, though perhaps with reduced functionality. In the same vein an implementation which does include a particular option MUST be prepared to interoperate with another implementation which does not include the option (except, of course, for the feature the option provides.)

**Comment by ecureuill** [comment]
@solex2006  As in #9 , teachers could benefit from a more flexible approach
[See comment](https://github.com/solex2006/SELIProject/issues/9#issuecomment-586665682)

**Comment by ecureuill** [comment]
# Failures

- [ ] due to not give teacher the option to upload an "audio description" in (.vtt) file
**Give teacher the option to upload an _audio description_ file (.vtt) OR  an alternative  _audio track_ (audio file)**
![image](https://user-images.githubusercontent.com/993369/91652487-38e42780-ea6e-11ea-9d83-045900ad488b.png)
