### ISSUE TITLE
Bugs in Quiz Feature

### ISSUE THREAD

**Issue by caroltaus** [solex2006/SELIProject#148]
### TASKS

- [ ] It is possible for the tutor to select a “deleted” answer or a blank answer as the correct one
When you save a quiz through the “Edit content” button it only checks for blank and “deleted” answers on the current question you’re editing, and not all questions of the quiz 

![image](https://user-images.githubusercontent.com/48024795/82614335-ff15a200-9b9d-11ea-9897-2beca60a5359.png)
_The first question had 4 answers deleted, but they are still counted for the student’s answers and influence their grade_

Steps to Reproduce “Blank Answer”:
1. Create a quiz
2. Create a normal question with answers
3. Create a new question with a “correct” answer but without any text
4. Go back to the previous question
5. Save it

Steps to Reproduce “Deleted Answer” in video at **00:00** and **00:30**

- [ ] It is possible to create a question with no correct answers, as shown in video at **1:07**

- [ ] When editing a quiz if the user closes the window (“X” button) instead of saving, the quiz, automatically, saves with 10 questions

![image](https://user-images.githubusercontent.com/48024795/82614464-51ef5980-9b9e-11ea-9bce-a3dd5e411072.png)
_How the student sees the automatically created questions_

![image](https://user-images.githubusercontent.com/48024795/82614505-6f242800-9b9e-11ea-892b-55eb89553a3d.png)
_It’s impossible to delete the automatically created questions_

![image](https://user-images.githubusercontent.com/48024795/82614625-a98dc500-9b9e-11ea-900b-2f791505fcca.png)
_Automatically created questions appear as blank_

Steps to Reproduce in video at **1:42**

- [ ] When user tries to decrease the number of answers (by clicking on the minus button, “ - ”) the number stays the same and instead of deleting the answer fields they stay on the page, only with their text hidden (when you click on it, the answer appears) 

![image](https://user-images.githubusercontent.com/48024795/82614734-eeb1f700-9b9e-11ea-80e2-aad9bb1ea4ad.png)

Steps to Reproduce:
1. Create a quiz
2. increase the number of answers to 8 
3. add some text (optional)
4. decrease the number of answers by clicking on the minus button “ - “

Shown in video at **2:14**

- [ ] Grades appear as a recurring decimal. Could be rounded to 2 decimals.
![image](https://user-images.githubusercontent.com/48024795/82614808-1acd7800-9b9f-11ea-9f92-f25b9e090410.png)

### VIDEO
https://drive.google.com/file/d/1TjD9pJlu_8SIOs9FFMmNmUNcIO56jD8Y/view

0:00 - Publishing a quiz with a deleted answer and a normal answer as correct

0:30 - Publishing a quiz with only a deleted answer as correct 

1:07 - Publishing a quiz without a correct answer and the system doesn't check if the question has a correct answer after one successful validation.

1:42 - When editing a quiz if the user closes the window (“X” button) instead of saving, the quiz, automatically, saves with 10 questions 

2:14 - When user tries to decrease the number of answers (by clicking on the minus button, “ - ”) the number stays the same and instead of deleting the answer fields they stay on the page, only with their text hidden (when we click on it, the answer appears)
