### ISSUE TITLE
Course - Syllabus Page

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#166]
# Page HTML Structure
https://codesandbox.io/s/prototype-tsz10?file=/course/syllabus.js

# Accessibility
- [ ] #114 Table of Conten (ToC)
- [ ] #110 Skip Link to ToC

**Comment by ecureuill** [comment]
# accessibility
The same modal dialog has `role` and others attributes defined more than one time, this prevent assistive technologies to work properly. Check the WAI-ARIA Practice example code to fix it and use ChromeVox to test if your solution is working. 
 
![image](https://user-images.githubusercontent.com/993369/91081816-17261300-e61e-11ea-8e55-0aeff67bff92.png)

![image](https://user-images.githubusercontent.com/993369/91081608-c1ea0180-e61d-11ea-87cc-6865ccda7ddb.png)

**Comment by ecureuill** [comment]
- [ ] :bomb: Syllabus is crashing with a blank page (check with Juan if is the same problem of preview crashing #143 )
```
c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9 TypeError: Cannot read property 'length' of undefined
    at s (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:131)
    at ki (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9)
    at kl (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9)
    at Yl (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9)
    at Xl (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9)
    at Vl (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9)
    at c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9
    at t.unstable_runWithPriority (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9)
    at uo (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9)
    at vo (c0bae6d7666d0b255aca1ebb26ea4428dd8afd82.js?meteor_js_resource=true:9)

```
```
propiedades en silabus 
{courseInformation: {…}, language: {…}}
courseInformation:
accessibility: Array(3)
0:
audienceError: false
audienceallError: true
audienceallgolError: true
audiencegolError: false
__proto__: Object
1:
audienceError: false
audienceallError: true
audienceallgolError: true
audiencegolError: false
__proto__: Object
2:
learningobjectives: false
modality: false
outcomes: false
pedagogical: false
__proto__: Object
length: 3
__proto__: Array(0)
analysis: Array(5)
0: null
1: "online"
2: "sdfsdfsdfsdf"
3:
analyzing: []
applying: []
creating: Array(1)
0: {label: "esdfsdf", aux: "build", editing: false}
length: 1
__proto__: Array(0)
evaluating: Array(1)
0: {label: "sfsdf", aux: "conclude", editing: false}
length: 1
__proto__: Array(0)
remembering: []
understanding: []
__proto__: Object
4:
contents: Array(1)
0: {label: "sdfsdf", aux: "understand", editing: false}
length: 1
__proto__: Array(0)
skills: [{…}]
values: [{…}]
__proto__: Object
length: 5
__proto__: Array(0)
classroom: ["4wQ6zqA79xmD7Qve8"]
coursePlan: {guidedCoursePlan: "guided", courseTemplate: "without", courseStructure: "topic"}
createdBy: "cecureuil"
creationDate: Sun Aug 23 2020 16:39:29 GMT-0300 (Horário Padrão de Brasília) {}
description: "In this course we will create an accessible course for visual impaired students "
design: Array(1)
0:
activities: []
editing: false
evaluation: "sdfsdf"
key: "topic1"
learnGols: "sdsfsdf"
lessons: Array(1)
0:
activities: [{…}]
key: "lesson1"
title: "Lesson 01"
tools: Array(6)
0: {checked: false, key: "audio", label: "Audios"}
1: {checked: false, key: "games", label: "Games", items: Array(0)}
2: {checked: false, key: "images", label: "Images"}
3: {checked: false, key: "presentation", label: "Presentation", items: Array(0)}
4: {checked: false, key: "supplemantary", label: "Supplementary Text", items: Array(0)}
5: {checked: false, key: "videos", label: "Videos"}
length: 6
__proto__: Array(0)
__proto__: Object
length: 1
__proto__: Array(0)
mainContent: "sdfds"
preKnowledge: "sdfsdf"
title: "Images"
tools: Array(6)
0: {checked: false, key: "audio", label: "Audios"}
1: {checked: false, key: "games", label: "Games", items: Array(0)}
2: {checked: false, key: "images", label: "Images"}
3: {checked: false, key: "presentation", label: "Presentation", items: Array(0)}
4: {checked: false, key: "supplemantary", label: "Supplementary Text", items: Array(0)}
5: {checked: false, key: "videos", label: "Videos"}
length: 6
__proto__: Array(0)
__proto__: Object
length: 1
__proto__: Array(0)
duration: "010:00:00"
image: {_id: "8nwgGCoFT5PAxZwW7", size: 61320, type: "image/jpeg", name: "breakfast.jpg", meta: {…}, …}
keyWords: (3) ["Course planning ", "Wcag ", "Accessibility "]
language: 0
level: ""
program: Array(1)
0:
activities: []
items: Array(57)
0: {id: 0.828606917030871, type: "text", attributes: {…}}
1: {id: 0.41704387859581016, type: "text", attributes: {…}}
2: {id: 0.00006846139074201396, type: "text", attributes: {…}}
3: {id: 0.8172503491828862, type: "text", attributes: {…}}
4: {id: 0.5296233763903895, type: "text", attributes: {…}}
5: {id: 0.45455474278072217, type: "text", attributes: {…}}
6:
attributes: {image: {…}, hasDescription: true, description: "", title: "Info Example 1", descriptionWidth: "calc(100% - 500px)", …}
id: 0.7216791373139166
type: "image"
__proto__: Object
7: {id: 0.38579564528215293, type: "text", attributes: {…}}
8: {id: 0.9869666265832975, type: "text", attributes: {…}}
9: {id: 0.17682062017970268, type: "text", attributes: {…}}
10:
attributes: {image: {…}, hasDescription: true, description: "", title: "Info Example 2", descriptionWidth: "calc(100% - 500px)", …}
id: 0.21812135375388886
type: "image"
__proto__: Object
11: {id: 0.8558965033466848, type: "text", attributes: {…}}
12: {id: 0.290561764592177, type: "text", attributes: {…}}
13: {id: 0.5612006469093445, type: "text", attributes: {…}}
14: {id: 0.3906974459740855, type: "text", attributes: {…}}
15: {id: 0.39556859387879006, type: "text", attributes: {…}}
16:
attributes: {image: {…}, hasDescription: true, description: "", title: "Info Example 3", descriptionWidth: "calc(100% - 500px)", …}
id: 0.04995625509875423
type: "image"
__proto__: Object
17: {id: 0.9472487745874361, type: "text", attributes: {…}}
18: {id: 0.6510302825266872, type: "text", attributes: {…}}
19: {id: 0.7353093731207134, type: "text", attributes: {…}}
20:
attributes: {image: {…}, hasDescription: true, description: "", title: "Info Example 4", descriptionWidth: "calc(100% - 500px)", …}
id: 0.27266459918219743
type: "image"
__proto__: Object
21: {id: 0.1592484389389739, type: "text", attributes: {…}}
22: {id: 0.2853201410627888, type: "text", attributes: {…}}
23: {id: 0.6395309272562675, type: "text", attributes: {…}}
24: {id: 0.41441163302692363, type: "text", attributes: {…}}
25:
attributes: {image: {…}, hasDescription: true, description: "", title: "Info Example 5", descriptionWidth: "calc(100% - 500px)", …}
id: 0.49071882704728487
type: "image"
__proto__: Object
26: {id: 0.11618289558350936, type: "text", attributes: {…}}
27: {id: 0.3058031060532591, type: "text", attributes: {…}}
28: {id: 0.6936700047921374, type: "text", attributes: {…}}
29: {id: 0.4954323109688179, type: "text", attributes: {…}}
30: {id: 0.29674974106606866, type: "text", attributes: {…}}
31: {id: 0.4058469550975694, type: "text", attributes: {…}}
32:
attributes: {image: {…}, hasDescription: true, description: "", title: "Deco Example 1", descriptionWidth: "calc(100% - 500px)", …}
id: 0.05600070965170967
type: "image"
__proto__: Object
33: {id: 0.706193496151412, type: "text", attributes: {…}}
34: {id: 0.8647676120609069, type: "text", attributes: {…}}
35: {id: 0.800351819916953, type: "text", attributes: {…}}
36:
attributes: {image: {…}, hasDescription: true, description: "", title: "Deco Example 2", descriptionWidth: "calc(100% - 500px)", …}
id: 0.14344205514730057
type: "image"
__proto__: Object
37: {id: 0.3739538269136018, type: "text", attributes: {…}}
38: {id: 0.9603144096665865, type: "text", attributes: {…}}
39: {id: 0.47959216012710915, type: "text", attributes: {…}}
40: {id: 0.2600003234150976, type: "text", attributes: {…}}
41:
attributes: {image: {…}, hasDescription: true, description: "", title: "text Example 1", descriptionWidth: "calc(100% - 500px)", …}
id: 0.22183639372464614
type: "image"
__proto__: Object
42: {id: 0.023697990206846153, type: "text", attributes: {…}}
43: {id: 0.9748960954364647, type: "text", attributes: {…}}
44: {id: 0.1682780017708747, type: "text", attributes: {…}}
45:
attributes: {image: {…}, hasDescription: true, description: "", title: "Text Example 2", descriptionWidth: "calc(100% - 500px)", …}
id: 0.6192495567588423
type: "image"
__proto__: Object
46: {id: 0.675800242099037, type: "text", attributes: {…}}
47: {id: 0.0829938584078691, type: "text", attributes: {…}}
48: {id: 0.13434155126405978, type: "text", attributes: {…}}
49: {id: 0.6432173155876544, type: "text", attributes: {…}}
50: {id: 0.4555796900483218, type: "text", attributes: {…}}
51:
attributes: {image: {…}, hasDescription: true, description: "", title: "Complex Example 1", descriptionWidth: "calc(100% - 500px)", …}
id: 0.33413781537133946
type: "image"
__proto__: Object
52: {id: 0.2511342312401317, type: "text", attributes: {…}}
53: {id: 0.017837437456942773, type: "text", attributes: {…}}
54: {id: 0.27205483159201505, type: "text", attributes: {…}}
55:
attributes:
accessibility:
dataField: {longDescription: {…}, shortDescription: "Male peacock head", imagePurpose: "cplx", shortDescriptionError: false, longDescriptionError: false, …}
isA11Y: Array(2)
0: {name: "shortDescription", is_a11y: true}
1: {name: "longDescription", is_a11y: true}
length: 2
__proto__: Array(0)
percentage: 100
pureDecorative: false
__proto__: Object
alignment: "row"
description: ""
descriptionWidth: "calc(100% - 500px)"
hasDescription: true
image: {_id: "quHcn286kybzNEJ2r", name: "image-cplx-ex02.jpg", link: "https://vm2161.kaj.pouta.csc.fi/opt/Seli/UploadFil…/quHcn286kybzNEJ2r/original/quHcn286kybzNEJ2r.jpg"}
size: {width: 500, height: 300}
title: "Complex Example 2"
__proto__: Object
id: 0.609472459667268
type: "image"
__proto__: Object
56: {id: 0.7782708997357997, type: "text", attributes: {…}}
length: 57
__proto__: Array(0)
lessons: [{…}]
name: "Images"
__proto__: Object
length: 1
__proto__: Array(0)
published: true
report: Array(4)
0: 100
1: 100
2: 100
3: 100
length: 4
__proto__: Array(0)
requirements: Array(2)
0: [{…}]
1: [{…}]
length: 2
__proto__: Array(0)
signature: ""
stepscompleted: (8) [0, 2, 6, 7, 1, 4, 3, 5]
stepsflag: "saved"
subtitle: "Planning an accessible course in SELI-Platform"
support: Array(2)
0: Array(9)
0: {id: 0, value: "StudentsGrad", label: "Graduate Students", isChecked: true}
1: {id: 1, value: "StudentsInfor", label: "Informal Students", isChecked: false}
2: {id: 2, value: "Teachers", label: "Teachers and Professors", isChecked: true}
3: {id: 3, value: "Kids", label: "Preschool Kids", isChecked: false}
4: {id: 4, value: "post graduate student", label: "Post Graduate Students", isChecked: true}
5: {id: 5, value: "pregrade student", label: "Undergraduate  Students", isChecked: false}
6: {id: 6, value: "High School Students", label: "High School Students", isChecked: false}
7: {id: 7, value: "Middle School Students", label: "Middle School Students", isChecked: false}
8: {id: 8, value: "Elementary School Students", label: "Elementary School Students", isChecked: false}
length: 9
__proto__: Array(0)
1: Array(4)
0: {id: 0, value: "cog", label: "Cognitive disabilities", isChecked: false}
1: {id: 1, value: "Eld", label: "Diversity of Abilities", isChecked: false}
2: {id: 2, value: "Hear", label: "Hearing disabilities", isChecked: false}
3: {id: 3, value: "Vis", label: "Visual disabilities", isChecked: true}
length: 4
__proto__: Array(0)
length: 2
__proto__: Array(0)
title: "WCAG 2.1"
type: ""
_id: "hKu96y8YfreaPboMQ"
__proto__: Object
language: {studentAccount: "Student account", tutorAccount: "Tutor account", reuseImg: "reuse image", reuseAudio: "reuse audio", audiomessage: "Double click over the item to select", …}
__proto__: Object
```

```
props en content 
{data: Array(1), coursePlan: {…}, program: Array(1)}
coursePlan:
courseStructure: "topic"
courseTemplate: "without"
guidedCoursePlan: "guided"
__proto__: Object
data: Array(1)
0:
activities: []
editing: false
evaluation: "sdfsdf"
key: "topic1"
learnGols: "sdsfsdf"
lessons: Array(1)
0:
activities: Array(1)
0: {activity: "Example", type: "1", graded: true, group: 0, project: false, …}
length: 1
__proto__: Array(0)
key: "lesson1"
title: "Lesson 01"
tools: Array(6)
0: {checked: false, key: "audio", label: "Audios"}
1: {checked: false, key: "games", label: "Games", items: Array(0)}
2: {checked: false, key: "images", label: "Images"}
3: {checked: false, key: "presentation", label: "Presentation", items: Array(0)}
4: {checked: false, key: "supplemantary", label: "Supplementary Text", items: Array(0)}
5: {checked: false, key: "videos", label: "Videos"}
length: 6
__proto__: Array(0)
__proto__: Object
length: 1
__proto__: Array(0)
mainContent: "sdfds"
preKnowledge: "sdfsdf"
title: "Images"
tools: Array(6)
0: {checked: false, key: "audio", label: "Audios"}
1: {checked: false, key: "games", label: "Games", items: Array(0)}
2: {checked: false, key: "images", label: "Images"}
3: {checked: false, key: "presentation", label: "Presentation", items: Array(0)}
4: {checked: false, key: "supplemantary", label: "Supplementary Text", items: Array(0)}
5: {checked: false, key: "videos", label: "Videos"}
length: 6
__proto__: Array(0)
__proto__: Object
length: 1
__proto__: Array(0)
program: Array(1)
0:
activities: []
items: (57) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
lessons: [{…}]
name: "Images"
__proto__: Object
length: 1
__proto__: Array(0)
__proto__: Object
```

**Comment by ecureuill** [comment]
- [ ] Syllabus dialog is crashing when is a PDF file (course title: a11y curso teste 01)

**Comment by CAndresH** [comment]
Hello Camila I have some doubts about the course syllabus for the following cases:
When the teacher selects in course plan: guided-without-By topics or By units & lessons

in the demo, the content in the syllable course is filled with the data from the design step,
![image](https://user-images.githubusercontent.com/50594090/91767463-c96f5480-eba1-11ea-8623-11c3809c2468.png)

but for free-without-by topics or units, the design step does not have this information, you can only change the name of the unit and topic, in that case with what data should it be filled in?
![image](https://user-images.githubusercontent.com/50594090/91767522-e146d880-eba1-11ea-9fd3-9039b9342472.png)
I have made changes in the syllable, check them and tell me

Another doubt : about the wrong headings, could you send a screenshot with the correct heading hierarchy?

thanks

**Comment by ecureuill** [comment]
Hi! @CAndresH 

In the case of guided-without-By topics or By units & lessons, you can list the items using the ordered list tag `<ol>` 
1. Topic A
1. Topic B
1. Topic C
1. Topic D

 or 

1. Unit A
    1. Lesson X
    1. Lesson P
1. Unit B
    1. Lesson T
1. Unit C
1. Unit D
    1. Lesson O

**Comment by ecureuill** [comment]
> Another doubt : about the wrong headings, could you send a screenshot with the correct heading hierarchy?
You should follow the ToC structure, except for _Readings_ and _Assments methods_ that is
![image](https://user-images.githubusercontent.com/993369/91781520-e8d1a600-ebd0-11ea-998b-e914d8f650bc.png)

And as I already mentioned in the list of problems, Syllabus is not exactly the same content/presentation as the Course Main page. For instance, check the way **course description**, **education language** are presented
![image](https://user-images.githubusercontent.com/993369/91781800-a197e500-ebd1-11ea-9261-2d1dfd66ce10.png)

If you follow the demo structure, you solve the heading problems

**Comment by CAndresH** [comment]
Correct Camila now the syllable is dynamic (ToC) and I have placed the headings as you describe them in your demo, the bug error is also corrected, please check, thanks

**Comment by ecureuill** [comment]
- [ ] #202

@CAndresH please, move to CODED only when this feature is fully implemented: bugs reported in comments and requirements in OP

If you want that we test some partial solution, add a comment here with our @

**Comment by CAndresH** [comment]
hello everyone please comment what are the errors?, @ecureuill @caroltaus ,

**Comment by ecureuill** [comment]
Hi @CAndresH everything that is not checked as done in specification needs your attention.

**Comment by CAndresH** [comment]
@rebeccamello  @caroltaus , 
What content of the design should be in evaluation?

**Comment by caroltaus** [comment]
@CAndresH 
This information:
![image](https://user-images.githubusercontent.com/48024795/99689592-f1b27500-2a65-11eb-888f-bba9a13ffb3e.png)

**Comment by caroltaus** [comment]
- [ ] LearningApplyingObjectives are not being show in syllabus

> in course creation:
> ![image](https://user-images.githubusercontent.com/48024795/101816807-3e86ea00-3b00-11eb-9c91-0f5e8b24aebf.png)
> 
> in syllabus:
> ![image](https://user-images.githubusercontent.com/48024795/101816868-58283180-3b00-11eb-964d-b629f8580cc1.png)

-------------------------------------------

- [ ] Learning Constraints are not showing in syllabus (they are not being saved, apparently, because when you fill it in course creation, save the course, and then open the course in edition mode, they are not there anymore)

**Comment by CAndresH** [comment]
hi @caroltaus, please check now

**Comment by caroltaus** [comment]
LearningApplyingObjectives is still not appearing

> ![image](https://user-images.githubusercontent.com/48024795/102236694-8fb52600-3ed2-11eb-8a8d-67824333a9f7.png)
> ![image](https://user-images.githubusercontent.com/48024795/102236759-a5c2e680-3ed2-11eb-9161-02e90c372307.png)


In some cases, it is appearing with the wrong verb:

> ![image](https://user-images.githubusercontent.com/48024795/102237025-f20e2680-3ed2-11eb-851d-e1bd0dda74c3.png)
