### ISSUE TITLE
Alignment feature of Text Component enables teachers to create inaccessible content

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#173]
The text alignment feature enables teachers to create inaccessible content by letting teacher mix alignments

# How to fix
- [ ] do not enable to align text (**check with Solomon if is ok**); 

_OR_

Keep alignment feature and:
- [ ] meets Text Alignments requirements in section 3.iv in #138 
- [ ] add option of accessibility configuration to text component and update #45 
- [ ] meets Text Alignment validations of section 3.vii in #138

**Comment by juantenesaca** [comment]
@ecureuill I do not understand the part to ask Solomon or resolve this
