### ISSUE TITLE
Instructional Design

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#60]
Author: Maria Amelia
*************************
# Currently proposal
https://docs.google.com/presentation/d/1DCEnK_naWWVsk7SnQb_wOjANEGMHkm4Qu4KNcPSuSxI/edit?usp=sharing

# Features specifications created
#72 
#73 

# Resources

[What are Spiral, Metaphor and Toy box models?](https://drive.google.com/open?id=1_Zy8vB0XR9xP5azRRfyrH8eACLSUl7mP)
**************************
# Current pending tasks for proposal
- [x] No _mouse over_.   All necessary information should be presented in the page if possible. Could use the current accessibility pattern of feedback ( see #46 )
- [ ] When the template models are finished
  - [ ] Define the correspondent html5 [semantic structures](https://www.semrush.com/blog/semantic-html5-guide/
)
 - [ ] Layout alternative of templates in one column 
 - [x] Update list of audiences
- [ ] Remove  from disabilities **motor impairments** and **Others**

** Information step ** 
- [x] Instead of “Course description” should be “Brief course description”, so the user won’t mistake it with the syllabus (Course Plan).
- [x] Remove syllabus pdf upload link.

![image](https://user-images.githubusercontent.com/993369/79526537-e44e8b80-803b-11ea-8d88-6ea43d9fd1f0.png)

![image](https://user-images.githubusercontent.com/993369/79526580-f6302e80-803b-11ea-8bce-342228610af1.png)

![image](https://user-images.githubusercontent.com/993369/79531248-28478d80-8048-11ea-8607-4501244963dd.png)

![image](https://user-images.githubusercontent.com/993369/79521094-b1ea6180-802e-11ea-8941-8696d471e983.png)
** Audience **
- [x] Target audience: update target audience options (remove options like “Mathematics”, “Computing” and “Pedagogy”).
- [ ] Better responsiveness for mobile and medium-sized screens when displaying options (avoid displaying all of them one on top of the other).
- [x] Disabilities: User can choose which types of disabilities they want their course to be accessible to.
- [ ] Disabilities options have an “?” icon with its explanation. (Same texts that are in the Requirements page today).

**Template:**
- [x] User chooses if they want to create the course freely or using a template:
- [x] If user already has a course plan: system must display an upload link for the syllabus, which should not be displayed if user does not have a course plan.
- [x] If user chooses to use a template, they will have to complete the “Analysis” and “Design” steps, otherwise those will be skipped.

Requirements:
- [x] Technical (hardware, software) and Prerequisites (previous knowledge). This step is described in Issue 56: #56

- [x] Analysis:
Information previously inputted at the Information and Audiences Pages should appear filled in. (Ex. Course title, subtitle, disabilities, etc...)

**Design:**
- [ ] User chooses if they want to organize their course by: Units (Spiral Model), Topics (Consistent Metaphor Model) or Problems (Toy Box Model).
- [ ] Each option has an “?” icon with an explanation of the course model.
- [ ] Insert a “Help me decide” box that suggests a course model to the user according to their answers to questions about their course.
- [ ] User, then, has to fill in the form with the Unit/Topic/Problem objective, materials, activity types...
- [ ] Map activity types options with activity types that exist in the authoring tool
- [ ] Create button to add more Units/Topics/Problems

**Program:**
- [ ] User fills in following the template chosen or freely with the content they want.

**First Page:**
- [ ] show syllabus in first page
- [ ] show audience in first page
- [ ] Change "Accessibility tool" for "This course is accessible for..."
*************************
**Evaluation**
- [ ] Activity component must have a option to evaluate it.
- [ ] Teacher panel where to manage the received activities / quiz and evaluate them

The live-demo of the steps
https://tsz10.csb.app/

**Comment by ecureuill** [comment]
If I understood, there is no conditional between **course plan** and **instructional template**, right? I.e. couse plan will  always  be created with same data, regardless of the chosen template.

Also, the **course plan**  is the same as  *Information step* of the current version of SELI, right?
 

If both statements are correct and if necessary, could change the name of the step 1 from **Information** for **Course Plan**
![image](https://user-images.githubusercontent.com/993369/78717940-c1173400-78f7-11ea-8c61-93f4cfa8b823.png)

******

The template selection could be included as step and the current Program step cold be disabled until teacher select a template (or none)   
![image](https://user-images.githubusercontent.com/993369/78720545-48ff3d00-78fc-11ea-954f-51ed438b9e1c.png)

******

Can I change the template when the program step is in development or finished?
For instance, I selected the Spiral template. I started to create some contents and then I realize that Toy Box fits better. 

******

# Necessary adjustments

- [ ] No mouse over option. All necessary information should be presented in the page if possible. Could use the current accessibility pattern of feedback ( see #46 )

**Comment by MAmelia** [comment]
Also, the course plan is the same as Information step of the current version of SELI, right?
No. The course plan envolves two phases: analysis and design. 
In the Analysis Phase we provide details on audience and learning strategies.
From the analysis and design phases the system will provide some information for the templates (Spiral, Consistent Metaphor and Toy Box), such as course title, objectives, title of each units, among others.

**Comment by MAmelia** [comment]
In the course plan, the accessibility requirements will be chosen in the analysis phase.

**Comment by ecureuill** [comment]
> No. The course plan envolves two phases: analysis and design. 
> In the Analysis Phase we provide details on audience and learning strategies.
> From the analysis and design phases the system will provide some information for the templates (Spiral, Consistent Metaphor and Toy Box), such as course title, objectives, title of each units, among others.

So,  I guess that most of (or all) data of the *Information* step will be encompasses in Design Phase. 

It's possible to create each one as steps. The *Template selection* step could keep disabled until all necessary information is provided in those steps. 
Also, the program step will be enabled when the Template step is completed.

I will update this comment with a live demo of the steps mechanics.

**Comment by MAmelia** [comment]
Can I change the template when the program step is in development or finished?
For instance, I selected the Spiral template. I started to create some contents and then I realize that Toy Box fits better.

Yes. Choices need to be flexible. The tutor can choose the Spiral Model and if he / she regrets, he / she can change. Probably, in this change he / she will lose the content information entered. The system needs to warn you of this in case of changes.
Another change that can occur: in the design phase the tutor will inform the number of units that the course will have. This information will be used by the system to establish the number of screens for the template. But the teacher can change this number of units in the form of the design phase and automatically the number of screens in the template will have to be changed. The system needs to be prepared for these changes.
It is also important for the tutor to have a preview of the pages he is creating.

**Comment by MAmelia** [comment]
> > No. The course plan envolves two phases: analysis and design.
> > In the Analysis Phase we provide details on audience and learning strategies.
> > From the analysis and design phases the system will provide some information for the templates (Spiral, Consistent Metaphor and Toy Box), such as course title, objectives, title of each units, among others.
> 
> So, I guess that most of (or all) data of the _Information_ step will be encompasses in Design Phase.
> 
> It's possible to create each one as steps. The _Template selection_ step could keep disabled until all necessary information is provided in those steps.
> Also, the program step will be enabled when the Template step is completed.
> 
> I will update this comment with a live demo of the steps mechanics.

With the model, the tutor will insert the content, as in the program step. That is, the program step will be the template.

**Comment by ecureuill** [comment]
I added new steps: **Analyse**, **Design** and **Template**

Here is the live demo
https://tsz10.csb.app/

How to use the demo:
- Previous and Next buttons navigate through the steps
  - It simulate that a step is left incomplete by the user
- Skip button is enabled when a step is optional
- Complete button is to set a step as completed  (required or optional steps)
- Publish button is only enabled when all steps is set as completed or skipped
- Conditional steps
  - Analyse must be completed to Design be enabled
  - Design must be completed to Template be enabled
  - Template must be completed  to Program (Authoring Tool) be enabled

Analyse and Design steps host the instructional design forms 
![image](https://user-images.githubusercontent.com/993369/78736752-4a446000-7924-11ea-8d7d-f3a340406804.png)

![image](https://user-images.githubusercontent.com/993369/78736770-57f9e580-7924-11ea-9989-cfc4291e5b21.png)

Template step host the template selector
![image](https://user-images.githubusercontent.com/993369/78736805-6f38d300-7924-11ea-84e8-9d857aeeb2a5.png)

**Comment by ecureuill** [comment]
Meeting 2020-04-08
@MAmelia 
@rsg73626 
@caroltaus 
@Valfarinazzo 
Flavio
Eduardo

*****

- Analysis and Design phases is not obligatory, teacher could upload a PDF.
  - How templates will work in this scenario?
- Information step: minimum data for save a course

# Tasks / Required changes
- [ ] Update list of audiences
  - Open a issue for development environment too
- [ ] Remove  from disabilities **motor impairments** and **Others**
- [ ] Disabilities goes to Analysis step, remove from **Requirement step**

**Comment by caroltaus** [comment]
Meeting 2020-04-13 

@MAmelia 

@Valfarinazzo 

@ecureuill 

@caroltaus 

@EduKobaiashi  

@rebeccamello  

Flavio 
 

###    Discussed Alterations in Course Creating 

- Page 1 - Information:  
  - General course information necessary to all courses (using templates or not).  
  - Instead of “Course description” should be “Brief course description”, so the user won’t mistake it with the syllabus (Course Plan).  
  - Remove syllabus pdf upload link.  

- Page 2 - Audience: 
  - Target audience: update target audience options (remove options like “Mathematics”, “Computing” and “Pedagogy”).  
  - Better responsiveness for mobile and medium-sized screens when displaying options (avoid displaying all of them one on top of the other). 
  - Disabilities: User can choose which types of disabilities they want their course to be accessible to. 
  - Disabilities options have an “?” icon with its explanation. (Same texts that are in the Requirements page today). 

- Page 3 - Template:  
  - User chooses if they want to create the course freely or using a template:   

  - If user already has a course plan: system must display an upload link for the syllabus, which should not be displayed if user does not have a course plan. 

  - If user chooses to use a template, they will have to complete the “Analysis” and “Design” steps, otherwise those will be skipped. 

  
- Page 4 - Requirements:   

  - Technical (hardware, software) and Prerequisites (previous knowledge). This step is described in Issue 56: https://github.com/solex2006/SELIProject/issues/56 

   

- Page 5 - Analysis: 
  - Information previously inputted at the Information and Audiences Pages should appear filled in. (Ex. Course title, subtitle, disabilities, etc...) 

- Page 6 - Design: 

  - User chooses if they want to organize their course by: Units (Spiral Model), Topics (Consistent Metaphor Model) or Problems (Toy Box Model). 

  - Each option has an “?” icon with an explanation of the course model. 

  - Insert a “Help me decide” box that suggests a course model to the user according to their answers to questions about their course. 

  - User, then, has to fill in the form with the Unit/Topic/Problem objective, materials, activity types... 

  - Map activity types options with activity types that exist in the authoring tool 

  - Create button to add more Units/Topics/Problems 

 
![addbutton](https://user-images.githubusercontent.com/48024795/79159510-9b35d780-7dae-11ea-80ec-58f1d531f1e6.PNG)

_Example button_ 

 
- Page 7 - Program:  

  - User fills in following the template chosen or freely with the content they want.

**Comment by ecureuill** [comment]
> Author: Maria Amelia
> 
> # Currently proposal
> https://docs.google.com/presentation/d/1DCEnK_naWWVsk7SnQb_wOjANEGMHkm4Qu4KNcPSuSxI/edit?usp=sharing
> 
> # Features specifications created
> #72
> #73
> 
> # Resources
> [What are Spiral, Metaphor and Toy box models?](https://drive.google.com/open?id=1_Zy8vB0XR9xP5azRRfyrH8eACLSUl7mP)
> 
> # Current pending tasks for proposal
> * [x]  No _mouse over_.   All necessary information should be presented in the page if possible. Could use the current accessibility pattern of feedback ( see #46 )
> * [ ]  When the template models are finished
>   
>   * [ ]  Define the correspondent html5 [semantic structures](https://www.semrush.com/blog/semantic-html5-guide/)
> * [ ]  Layout alternative of templates in one column
> * [x]  Update list of audiences
> * [ ]  Remove  from disabilities **motor impairments** and **Others**
> 
> ** Information step **
> 
> * [x]  Instead of “Course description” should be “Brief course description”, so the user won’t mistake it with the syllabus (Course Plan).
> * [x]  Remove syllabus pdf upload link.
> 
> ![image](https://user-images.githubusercontent.com/993369/79526537-e44e8b80-803b-11ea-8d88-6ea43d9fd1f0.png)
> 
> ![image](https://user-images.githubusercontent.com/993369/79526580-f6302e80-803b-11ea-8bce-342228610af1.png)
> 
> ![image](https://user-images.githubusercontent.com/993369/79531248-28478d80-8048-11ea-8607-4501244963dd.png)
> 
> ![image](https://user-images.githubusercontent.com/993369/79521094-b1ea6180-802e-11ea-8941-8696d471e983.png)
> ** Audience **
> 
> * [x]  Target audience: update target audience options (remove options like “Mathematics”, “Computing” and “Pedagogy”).
> * [ ]  Better responsiveness for mobile and medium-sized screens when displaying options (avoid displaying all of them one on top of the other).
> * [x]  Disabilities: User can choose which types of disabilities they want their course to be accessible to.
> * [ ]  Disabilities options have an “?” icon with its explanation. (Same texts that are in the Requirements page today).
> 
> **Template:**
> 
> * [x]  User chooses if they want to create the course freely or using a template:
> * [x]  If user already has a course plan: system must display an upload link for the syllabus, which should not be displayed if user does not have a course plan.
> * [x]  If user chooses to use a template, they will have to complete the “Analysis” and “Design” steps, otherwise those will be skipped.
> 
> Requirements:
> 
> * [x]  Technical (hardware, software) and Prerequisites (previous knowledge). This step is described in Issue 56: #56
> * [x]  Analysis:
>   Information previously inputted at the Information and Audiences Pages should appear filled in. (Ex. Course title, subtitle, disabilities, etc...)
> 
> **Design:**
> 
> * [ ]  User chooses if they want to organize their course by: Units (Spiral Model), Topics (Consistent Metaphor Model) or Problems (Toy Box Model).
> * [ ]  Each option has an “?” icon with an explanation of the course model.
> * [ ]  Insert a “Help me decide” box that suggests a course model to the user according to their answers to questions about their course.
> * [ ]  User, then, has to fill in the form with the Unit/Topic/Problem objective, materials, activity types...
> * [ ]  Map activity types options with activity types that exist in the authoring tool
> * [ ]  Create button to add more Units/Topics/Problems
> 
> **Program:**
> 
> * [ ]  User fills in following the template chosen or freely with the content they want.
> 
> **First Page:**
> 
> * [ ]  show syllabus in first page
> * [ ]  show audience in first page
> * [ ]  Change "Accessibility tool" for "This course is accessible for..."
> 
> **Evaluation**
> 
> * [ ]  Activity component must have a option to evaluate it.
> * [ ]  Teacher panel where to manage the received activities / quiz and evaluate them
> 
> The live-demo of the steps
> https://tsz10.csb.app/

**Comment by ecureuill** [comment]
Meeting 2020-05-21
@solex2006 
Equator Team
Brazilian Team
Uruguay Team

# Modifications
- [ ] Remove suggested softwares and hardwares from **requirement step**. Keep only open options
- [ ] Keep 6 suggested phrases for Broom Taxonomy and open option in **Analyses step**
